CREATE DATABASE IF NOT EXISTS NOP;

USE NOP;

CREATE TABLE IF NOT EXISTS ACCOUNT(
    ACCOUNTID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    USERFNAME VARCHAR(50),
    USERLNAME VARCHAR(50),
    USERTYPE ENUM('STUDENT','ADMIN','COURSEMANAGER') NOT NULL
);

CREATE TABLE IF NOT EXISTS COURSE(
    COURSEID INT AUTO_INCREMENT PRIMARY KEY,
    COURSENAME VARCHAR(50),
    COURSENUMBER INT 
);

CREATE TABLE IF NOT EXISTS ENROLLMENT(
    ENROLLMENTID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNTID INT NOT NULL,
    COURSEID INT NOT NULL,
    ISMANAGER BOOLEAN NOT NULL,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE,
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TEAM(
    TEAMID INT AUTO_INCREMENT PRIMARY KEY,
    COURSEID INT NOT NULL,
    TEAMNAME VARCHAR(50),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SURVEY(
    SURVEYID INT AUTO_INCREMENT PRIMARY KEY,
    COURSEID INT NOT NULL,
    SURVEYTITLE VARCHAR(50),
    TEAMBASED BOOLEAN,
    NUMQUESTIONS INT,
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TEAMMEMBERSHIP(
    MEMBERSHIPID INT AUTO_INCREMENT PRIMARY KEY,
    TEAMID INT NOT NULL,
    ACCOUNTID INT NOT NULL,
    SURVEYID INT NOT NULL,
    FOREIGN KEY (TEAMID) REFERENCES TEAM(TEAMID) ON DELETE CASCADE,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE,
    FOREIGN KEY (SURVEYID) REFERENCES SURVEY(SURVEYID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUESTION(
    QUESTIONID INT AUTO_INCREMENT PRIMARY KEY,
    SURVEYID INT NOT NULL,
    QUESTION VARCHAR(100),
    QUESTIONTYPE ENUM('RRESPONSE','PRESPONSE','ORESPONSE','NRESPONSE'),
    QUESTIONNUM INT,
    FOREIGN KEY (SURVEYID) REFERENCES SURVEY(SURVEYID) ON DELETE CASCADE  
);

CREATE TABLE IF NOT EXISTS RESPONSE(
    RESPONSEID INT AUTO_INCREMENT PRIMARY KEY,
    QUESTIONID INT NOT NULL,
    ACCOUNTID INT NOT NULL,
    RRESPONSE VARCHAR(500),
    PRESPONSE DOUBLE,
    ORESPONSE VARCHAR(500),
    NRESPONSE INT
);


-- password: "password"
INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('cgowen00@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'caleb', 'gowen', 'STUDENT'); 

INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('Rafe@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'Rafe', 'wilhite', 'STUDENT');

INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('admin@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'admin', 'admin', 'ADMIN'); 

INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('Josue@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'Josue', 'Josue', 'STUDENT'); 

INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('Blake@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'Blake', 'Blake', 'STUDENT'); 


INSERT INTO COURSE (COURSENAME, COURSENUMBER)
VALUES ('FORMAL', '4902');

INSERT INTO COURSE (COURSENAME, COURSENUMBER)
VALUES ('Cal', '4901');

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (1, 1, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (2, 1, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (4, 1, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (5, 1, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (1, 2, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (2, 1, TRUE);

INSERT INTO TEAM (COURSEID, TEAMNAME)
VALUES (1, 'TEAM ONE');

INSERT INTO TEAM (COURSEID, TEAMNAME)
VALUES (1, 'Demo Team');

INSERT INTO TEAM (COURSEID, TEAMNAME)
VALUES (1, 'Demo2 Team');

INSERT INTO SURVEY (COURSEID, SURVEYTITLE, TEAMBASED, NUMQUESTIONS)
VALUES (1,'TEAM SURVEY', TRUE, 1);

INSERT INTO SURVEY (COURSEID, SURVEYTITLE, TEAMBASED, NUMQUESTIONS)
VALUES (1,'Demo Survey', TRUE, 4);

INSERT INTO SURVEY (COURSEID, SURVEYTITLE, TEAMBASED, NUMQUESTIONS)
VALUES (2,'Demo Survey 2', TRUE, 3);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (1, 1, 1);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (1, 2, 1);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (2, 1, 2);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (2, 4, 2);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (2, 5, 2);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (3, 1, 3);

INSERT INTO TEAMMEMBERSHIP (TEAMID, ACCOUNTID, SURVEYID)
VALUES (3, 5, 3);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (1, 'Question 1','ORESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (1, 'Question 2','RRESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (1, 'Question 3','PRESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (1, 'Question 4','NRESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (2, 'This is an open response question?','ORESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (2, 'This is a team ranked response question?','RRESPONSE', 2);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (2, 'This is a percentage response question?','PRESPONSE', 3);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (2, 'This is an open response question?','ORESPONSE', 4);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (3, 'This is an open response question?','ORESPONSE', 1);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (3, 'This is a percentage response question?','PRESPONSE', 2);

INSERT INTO QUESTION (SURVEYID, QUESTION, QUESTIONTYPE, QUESTIONNUM)
VALUES (3, 'This is an open response question?','ORESPONSE', 3);

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, ORESPONSE)
VALUES (1, 1, 'ANSWER');

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, RRESPONSE)
VALUES (2, 1, 'Fifty Sevey');

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, PRESPONSE)
VALUES (3, 1, 0.25);

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, NRESPONSE)
VALUES (4, 1, 5);

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, ORESPONSE)
VALUES (1, 2, 'ANSWER 2');

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, RRESPONSE)
VALUES (2, 2, 'Baked Beans');

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, PRESPONSE)
VALUES (3, 2, 0.87);

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, NRESPONSE)
VALUES (4, 2, 6);

INSERT INTO RESPONSE (QUESTIONID, ACCOUNTID, ORESPONSE)
VALUES (5, 4, 'Test answer');

-- Carter
INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('carter@test.com', '730f7d03509cce2ddaed4203d62baac9b68d92824a9bafbe14c0214c82bf7fb4', 'Carter', 'Carter', 'STUDENT');

INSERT INTO ACCOUNT (EMAIL, PASSWORD, USERFNAME, USERLNAME, USERTYPE)
VALUES ('manager@uafs.edu', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'manager', 'manager', 'COURSEMANAGER');

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (7, 1, true);

INSERT INTO COURSE (COURSENAME, COURSENUMBER)
VALUES ('SWE', '6666');

INSERT INTO COURSE (COURSENAME, COURSENUMBER)
VALUES ('COMBINATORICS', '1234');

INSERT INTO COURSE (COURSENAME, COURSENUMBER)
VALUES ('DEEP LEARNING', '5861');


INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (6, 1, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (6, 3, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (6, 4, false);

INSERT INTO ENROLLMENT (ACCOUNTID, COURSEID, ISMANAGER)
VALUES (6, 5, false);

-- Add a dev for the database
CREATE USER 'dev'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON NOP.* TO 'dev'@'localhost';
FLUSH PRIVILEGES;